name       : CGAL
version    : 4.9
release    : 1
source     :
    - https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.9/CGAL-4.9.tar.xz : 63ac5df71f912f34f2f0f2e54a303578df51f4ec2627db593a65407d791f9039
license    :
    - BSL-1.0
    - GPL-3.0
    - LGPL-3.0
    - MIT
component  : programming
summary    : Computational Geometry Algorithms Library
description: |
    Computational Geometry Algorithms Library
builddeps  :
    - pkgconfig(QtCore)
    - libboost-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DQT_MOC_EXECUTABLE=moc-qt4 \
           -DQT_RCC_EXECUTABLE=rcc-qt4 \
           -DQT_UIC_EXECUTABLE=uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
