name       : CGAL
version    : 4.13
release    : 2
source     :
    - https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.13/CGAL-4.13.tar.xz : 3e3dd7a64febda58be54c3cbeba329ab6a73b72d4d7647ba4931ecd1fad0e3bc
license    :
    - BSL-1.0
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MIT
component  : programming
summary    : Computational Geometry Algorithms Library
description: |
    Computational Geometry Algorithms Library
builddeps  :
    - pkgconfig(Qt5Svg)
    - libboost-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
