name       : CGAL
version    : 5.0.2
release    : 4
source     :
    - https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-5.0.2/CGAL-5.0.2.tar.xz : bb3594ba390735404f0972ece301f369b1ff12646ad25e48056b4d49c976e1fa
license    :
    - BSL-1.0
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MIT
component  : programming
summary    : Computational Geometry Algorithms Library
description: |
    Computational Geometry Algorithms Library
builddeps  :
    - pkgconfig(Qt5Svg)
    - libboost-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
